spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/booksky
    username: postgres
    password: gs2112004@
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  show-sql: true
server:
  port: 8080